[package]
name = "drm_prime_sink"
version = "0.1.0"
edition = "2024"

[lib]
name = "drm_prime_sink"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
drm = "0.14"  # aka "drm-rs"
rustler = "0.36.2"
drm-ffi = "0.9"
libc = "0.2"
drm-fourcc = "2.2"

[features]
default = []
verbose = []          # enable to keep println-style logs

[profile.release]
opt-level = "z"       # optimize for size
lto = "fat"           # best size (slower build)
codegen-units = 1
panic = "abort"
strip = "symbols"     # strip in Cargo (or run `strip -s` afterwards)
