[package]
name = "h265decoder"
version = "0.1.0"
edition = "2024"

[lib]
name = "h265decoder"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
ffmpeg-next = { version = "7.1", features = ["codec", "format", "software-scaling", "static", "build"] }
ffmpeg-sys-next = { version = "7.1", features = ["build", "static"] }
rustler = "0.36"
libc = "0.2"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
